# Generated by Django 5.1.2 on 2025-10-22 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('itemType', models.CharField(choices=[('EVE', 'Event'), ('SEG', 'Segment'), ('SER', 'Series'), ('TSE', 'TimeSeries')], default='SER', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='TimeSeriesPlotPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('value', models.FloatField()),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flowerapp.track')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('detail1', models.CharField(blank=True, max_length=100, null=True)),
                ('detail2', models.CharField(blank=True, max_length=100, null=True)),
                ('start', models.DateField()),
                ('end', models.DateField(blank=True, null=True)),
                ('startTime', models.TimeField(blank=True, null=True)),
                ('endTime', models.TimeField(blank=True, null=True)),
                ('img', models.URLField(blank=True, max_length=500, null=True)),
                ('additional_info', models.URLField(blank=True, max_length=500, null=True)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flowerapp.track')),
            ],
        ),
    ]
